/* Generated by Pyrex 0.9.8.5 on Tue Oct 20 11:38:50 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "logmath.h"
#include "cmd_ln.h"
#include "ckd_alloc.h"
#include "fsg_model.h"
#include "ngram_model.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[],     Py_ssize_t nargs, PyObject **args2, PyObject **kwds2, char rqd_kwds[]); /*proto*/

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from sphinxbase */

typedef float __pyx_t_10sphinxbase_float32;

typedef int __pyx_t_10sphinxbase_int32;

typedef double __pyx_t_10sphinxbase_float64;

struct __pyx_obj_10sphinxbase_NGramModel {
  PyObject_HEAD
  struct __pyx_vtabstruct_10sphinxbase_NGramModel *__pyx_vtab;
  ngram_model_t *lm;
  logmath_t *lmath;
  float lw;
  float wip;
  float uw;
};

struct __pyx_obj_10sphinxbase_LogMath {
  PyObject_HEAD
  logmath_t *lmath;
};

struct __pyx_obj_10sphinxbase_NGram {
  PyObject_HEAD
  float log_prob;
  float log_bowt;
  PyObject *words;
};

struct __pyx_obj_10sphinxbase_NGramIter {
  PyObject_HEAD
  struct __pyx_obj_10sphinxbase_NGramModel *lm;
  ngram_iter_t *itor;
  int first_item;
  int m;
};


struct __pyx_vtabstruct_10sphinxbase_NGramModel {
  PyObject *(*set_lm)(struct __pyx_obj_10sphinxbase_NGramModel *,ngram_model_t *);
  PyObject *(*set_lmath)(struct __pyx_obj_10sphinxbase_NGramModel *,logmath_t *);
};
static struct __pyx_vtabstruct_10sphinxbase_NGramModel *__pyx_vtabptr_10sphinxbase_NGramModel;




static PyTypeObject *__pyx_ptype_10sphinxbase_NGramModel = 0;
static PyTypeObject *__pyx_ptype_10sphinxbase_LogMath = 0;
static PyTypeObject *__pyx_ptype_10sphinxbase_NGram = 0;
static PyTypeObject *__pyx_ptype_10sphinxbase_NGramIter = 0;

/* Declarations from implementation of sphinxbase */


static char __pyx_k1[] = "range";
static char __pyx_k2[] = "append";

static PyObject *__pyx_n_append;
static PyObject *__pyx_n_range;


static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_append, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_range, 1, __pyx_k1, sizeof(__pyx_k1)},
  {0, 0, 0, 0}
};

static PyObject *__pyx_d1;
static PyObject *__pyx_d2;
static PyObject *__pyx_d3;
static PyObject *__pyx_d4;
static PyObject *__pyx_d5;
static PyObject *__pyx_d6;
static PyObject *__pyx_d7;
static PyObject *__pyx_d8;
static PyObject *__pyx_d9;
static PyObject *__pyx_d10;


/* Implementation of sphinxbase */

static int __pyx_f_10sphinxbase_7LogMath___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_10sphinxbase_7LogMath___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_base = 0;
  PyObject *__pyx_v_shift = 0;
  PyObject *__pyx_v_use_table = 0;
  int __pyx_r;
  __pyx_t_10sphinxbase_float64 __pyx_1;
  int __pyx_2;
  int __pyx_3;
  static char *__pyx_argnames[] = {"base","shift","use_table",0};
  __pyx_v_base = __pyx_d1;
  __pyx_v_shift = __pyx_d2;
  __pyx_v_use_table = __pyx_d3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOO", __pyx_argnames, &__pyx_v_base, &__pyx_v_shift, &__pyx_v_use_table)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_base);
  Py_INCREF(__pyx_v_shift);
  Py_INCREF(__pyx_v_use_table);
  __pyx_1 = PyFloat_AsDouble(__pyx_v_base); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_shift); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  __pyx_3 = PyInt_AsLong(__pyx_v_use_table); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath = logmath_init(__pyx_1,__pyx_2,__pyx_3);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("sphinxbase.LogMath.__cinit__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_base);
  Py_DECREF(__pyx_v_shift);
  Py_DECREF(__pyx_v_use_table);
  return __pyx_r;
}

static void __pyx_f_10sphinxbase_7LogMath___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_10sphinxbase_7LogMath___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);
  logmath_free(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath);

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_get_zero(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_get_zero[] = "\n        Get the log-zero value.\n\n        @return: Smallest number representable by this object.\n        @rtype: int\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_get_zero(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_1 = PyInt_FromLong(logmath_get_zero(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("sphinxbase.LogMath.get_zero");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_add(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_add[] = "\n        Add two numbers in log-space.\n\n        @param a: Logarithm A.\n        @type a: int\n        @param b: Logarithm B.\n        @type b: int\n        @return: log(exp(a)+exp(b))\n        @rtype: int\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_add(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_a = 0;
  PyObject *__pyx_v_b = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"a","b",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_a, &__pyx_v_b)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_a);
  Py_INCREF(__pyx_v_b);
  __pyx_1 = PyInt_AsLong(__pyx_v_a); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_v_b); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(logmath_add(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath,__pyx_1,__pyx_2)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("sphinxbase.LogMath.add");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_a);
  Py_DECREF(__pyx_v_b);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_log(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_log[] = "\n        Return log-value of a number.\n\n        @param x: Number (in linear space)\n        @type x: float\n        @return: Log-value of x.\n        @rtype: int\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_log(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_r;
  __pyx_t_10sphinxbase_float64 __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  __pyx_1 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(logmath_log(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.LogMath.log");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_exp(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_exp[] = "\n        Return linear of a log-value\n\n        @param x: Logarithm X (in this object\'s base)\n        @type x: int\n        @return: Exponent (linear value) of X.\n        @rtype: float\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_exp(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  __pyx_1 = PyInt_AsLong(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  __pyx_2 = PyFloat_FromDouble(logmath_exp(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.LogMath.exp");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_log_to_ln(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_log_to_ln[] = "\n        Return natural logarithm of a log-value.\n\n        @param x: Logarithm X (in this object\'s base)\n        @type x: int\n        @return: Natural log equivalent of x.\n        @rtype: float\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_log_to_ln(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  __pyx_1 = PyInt_AsLong(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_2 = PyFloat_FromDouble(logmath_log_to_ln(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.LogMath.log_to_ln");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_log_to_log10(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_log_to_log10[] = "\n        Return logarithm in base 10 of a log-value.\n\n        @param x: Logarithm X (in this object\'s base)\n        @type x: int\n        @return: log10 equivalent of x.\n        @rtype: float\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_log_to_log10(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  __pyx_1 = PyInt_AsLong(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_2 = PyFloat_FromDouble(logmath_log_to_log10(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.LogMath.log_to_log10");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_ln_to_log(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_ln_to_log[] = "\n        Return log-value of a natural logarithm.\n\n        @param x: Logarithm X (in base e)\n        @type x: float\n        @return: Log-value equivalent of x.\n        @rtype: int\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_ln_to_log(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_r;
  __pyx_t_10sphinxbase_float64 __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  __pyx_1 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(logmath_ln_to_log(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.LogMath.ln_to_log");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_7LogMath_log10_to_log(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_7LogMath_log10_to_log[] = "\n        Return log-value of a base 10 logarithm.\n\n        @param x: Logarithm X (in base 10)\n        @type x: float\n        @return: Log-value equivalent of x.\n        @rtype: int\n        ";
static PyObject *__pyx_f_10sphinxbase_7LogMath_log10_to_log(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_x = 0;
  PyObject *__pyx_r;
  __pyx_t_10sphinxbase_float64 __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);
  __pyx_1 = PyFloat_AsDouble(__pyx_v_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(logmath_log10_to_log(((struct __pyx_obj_10sphinxbase_LogMath *)__pyx_v_self)->lmath,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.LogMath.log10_to_log");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static int __pyx_f_10sphinxbase_10NGramModel___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_10sphinxbase_10NGramModel___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_file = 0;
  PyObject *__pyx_v_lw = 0;
  PyObject *__pyx_v_wip = 0;
  PyObject *__pyx_v_uw = 0;
  int __pyx_r;
  int __pyx_1;
  char *__pyx_2;
  __pyx_t_10sphinxbase_float32 __pyx_3;
  __pyx_t_10sphinxbase_float32 __pyx_4;
  __pyx_t_10sphinxbase_float32 __pyx_5;
  float __pyx_6;
  static char *__pyx_argnames[] = {"file","lw","wip","uw",0};
  __pyx_v_file = __pyx_d4;
  __pyx_v_lw = __pyx_d5;
  __pyx_v_wip = __pyx_d6;
  __pyx_v_uw = __pyx_d7;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOOO", __pyx_argnames, &__pyx_v_file, &__pyx_v_lw, &__pyx_v_wip, &__pyx_v_uw)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_file);
  Py_INCREF(__pyx_v_lw);
  Py_INCREF(__pyx_v_wip);
  Py_INCREF(__pyx_v_uw);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":146 */
  ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lmath = logmath_init(1.0001,0,0);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":147 */
  __pyx_1 = PyObject_IsTrue(__pyx_v_file); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; goto __pyx_L1;}
  if (__pyx_1) {

    /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":148 */
    __pyx_2 = PyString_AsString(__pyx_v_file); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
    ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm = ngram_model_read(NULL,__pyx_2,NGRAM_AUTO,((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lmath);

    /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":149 */
    __pyx_3 = PyFloat_AsDouble(__pyx_v_lw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    __pyx_4 = PyFloat_AsDouble(__pyx_v_wip); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    __pyx_5 = PyFloat_AsDouble(__pyx_v_uw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
    ngram_model_apply_weights(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_3,__pyx_4,__pyx_5);
    goto __pyx_L2;
  }
  /*else*/ {
    ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm = NULL;
  }
  __pyx_L2:;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":152 */
  __pyx_6 = PyFloat_AsDouble(__pyx_v_lw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lw = __pyx_6;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":153 */
  __pyx_6 = PyFloat_AsDouble(__pyx_v_wip); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 153; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->wip = __pyx_6;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":154 */
  __pyx_6 = PyFloat_AsDouble(__pyx_v_uw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->uw = __pyx_6;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("sphinxbase.NGramModel.__cinit__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_file);
  Py_DECREF(__pyx_v_lw);
  Py_DECREF(__pyx_v_wip);
  Py_DECREF(__pyx_v_uw);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_set_lm(struct __pyx_obj_10sphinxbase_NGramModel *__pyx_v_self,ngram_model_t *__pyx_v_lm) {
  PyObject *__pyx_r;
  Py_INCREF(__pyx_v_self);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":157 */
  ngram_model_retain(__pyx_v_lm);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":158 */
  ngram_model_free(__pyx_v_self->lm);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":159 */
  __pyx_v_self->lm = __pyx_v_lm;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_set_lmath(struct __pyx_obj_10sphinxbase_NGramModel *__pyx_v_self,logmath_t *__pyx_v_lmath) {
  PyObject *__pyx_r;
  Py_INCREF(__pyx_v_self);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":162 */
  logmath_retain(__pyx_v_lmath);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":163 */
  logmath_free(__pyx_v_self->lmath);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":164 */
  __pyx_v_self->lmath = __pyx_v_lmath;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static void __pyx_f_10sphinxbase_10NGramModel___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_10sphinxbase_10NGramModel___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":170 */
  logmath_free(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lmath);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":171 */
  ngram_model_free(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm);

  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_apply_weights(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_10NGramModel_apply_weights[] = "\n        Change the language model weights applied in L{score}.\n        \n        @param lw: Language weight to apply to model probabilities.\n        @type lw: float\n        @param wip: Word insertion penalty to add to model probabilities\n        @type wip: float\n        @param uw: Weight to give unigrams when interpolating with uniform distribution.\n        @type uw: float\n        ";
static PyObject *__pyx_f_10sphinxbase_10NGramModel_apply_weights(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_lw = 0;
  PyObject *__pyx_v_wip = 0;
  PyObject *__pyx_v_uw = 0;
  PyObject *__pyx_r;
  float __pyx_1;
  __pyx_t_10sphinxbase_float32 __pyx_2;
  __pyx_t_10sphinxbase_float32 __pyx_3;
  __pyx_t_10sphinxbase_float32 __pyx_4;
  static char *__pyx_argnames[] = {"lw","wip","uw",0};
  __pyx_v_lw = __pyx_d8;
  __pyx_v_wip = __pyx_d9;
  __pyx_v_uw = __pyx_d10;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|OOO", __pyx_argnames, &__pyx_v_lw, &__pyx_v_wip, &__pyx_v_uw)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_lw);
  Py_INCREF(__pyx_v_wip);
  Py_INCREF(__pyx_v_uw);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":184 */
  __pyx_1 = PyFloat_AsDouble(__pyx_v_lw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lw = __pyx_1;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":185 */
  __pyx_1 = PyFloat_AsDouble(__pyx_v_wip); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 185; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->wip = __pyx_1;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":186 */
  __pyx_1 = PyFloat_AsDouble(__pyx_v_uw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 186; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->uw = __pyx_1;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":187 */
  __pyx_2 = PyFloat_AsDouble(__pyx_v_lw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  __pyx_3 = PyFloat_AsDouble(__pyx_v_wip); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  __pyx_4 = PyFloat_AsDouble(__pyx_v_uw); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 187; goto __pyx_L1;}
  ngram_model_apply_weights(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_2,__pyx_3,__pyx_4);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("sphinxbase.NGramModel.apply_weights");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_lw);
  Py_DECREF(__pyx_v_wip);
  Py_DECREF(__pyx_v_uw);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_wid(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_10NGramModel_wid[] = "\n        Get the internal ID for a word.\n        \n        @param word: Word in question\n        @type word: string\n        @return: Internal ID for word\n        @rtype: int\n        ";
static PyObject *__pyx_f_10sphinxbase_10NGramModel_wid(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_word = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"word",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_word)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_word);
  __pyx_1 = PyString_AsString(__pyx_v_word); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(ngram_wid(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.NGramModel.wid");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_word);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_word(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_10NGramModel_word[] = "\n        Get the string corresponding to an internal word ID.\n        \n        @param word: Word ID in question\n        @type word: int\n        @return: String for word\n        @rtype: string\n        ";
static PyObject *__pyx_f_10sphinxbase_10NGramModel_word(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_wid = 0;
  PyObject *__pyx_r;
  __pyx_t_10sphinxbase_int32 __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {"wid",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_wid)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_wid);
  __pyx_1 = PyInt_AsLong(__pyx_v_wid); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
  __pyx_2 = PyString_FromString(ngram_word(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_1)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 209; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.NGramModel.word");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_wid);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_score(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_10NGramModel_score[] = "\n        Get the score for an N-Gram.\n\n        The argument list consists of the history words (as\n        null-terminated strings) of the N-Gram, in reverse order.\n        Therefore, if you wanted to get the N-Gram score for \"a whole\n        joy\", you would call::\n\n         score, n_used = model.score(\"joy\", \"whole\", \"a\")\n\n        This function returns a tuple, consisting of the score and the\n        number of words used in computing it (i.e. the effective size\n        of the N-Gram).  The score is returned in logarithmic form,\n        using base e.\n\n        If one of the words is not in the LM\'s vocabulary, the result\n        will depend on whether this is an open or closed vocabulary\n        language model.  For an open-vocabulary model, unknown words\n        are all mapped to the unigram <UNK> which has a non-zero\n        probability and also participates in higher-order N-Grams.\n        Therefore, you will get a score of some sort in this case.\n\n        For a closed-vocabulary model, unknown words are impossible\n        and thus have zero probability.  Therefore, if C{word} is\n        unknown, this function will return a \"zero\" log-probability,\n        i.e. a large negative number.\n        ";
static PyObject *__pyx_f_10sphinxbase_10NGramModel_score(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_word = 0;
  PyObject *__pyx_v_args = 0;
  __pyx_t_10sphinxbase_int32 __pyx_v_wid;
  __pyx_t_10sphinxbase_int32 *__pyx_v_hist;
  __pyx_t_10sphinxbase_int32 __pyx_v_n_hist;
  __pyx_t_10sphinxbase_int32 __pyx_v_n_used;
  __pyx_t_10sphinxbase_int32 __pyx_v_score;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_spam;
  PyObject *__pyx_r;
  char *__pyx_1;
  Py_ssize_t __pyx_2;
  long __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"word",0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 1, &__pyx_v_args, 0, 0) < 0) return 0;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_word)) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    return 0;
  }
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_word);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  __pyx_v_spam = Py_None; Py_INCREF(Py_None);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":245 */
  __pyx_1 = PyString_AsString(__pyx_v_word); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 245; goto __pyx_L1;}
  __pyx_v_wid = ngram_wid(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_1);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":246 */
  __pyx_2 = PyObject_Length(__pyx_v_args); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 246; goto __pyx_L1;}
  __pyx_v_n_hist = __pyx_2;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":247 */
  __pyx_v_hist = ((__pyx_t_10sphinxbase_int32 *)ckd_calloc(__pyx_v_n_hist,(sizeof(__pyx_t_10sphinxbase_int32))));

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":248 */
  for (__pyx_3 = 0; __pyx_3 < __pyx_v_n_hist; ++__pyx_3) {
    __pyx_4 = PyInt_FromLong(__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 248; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_4;
    __pyx_4 = 0;

    /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":249 */
    __pyx_4 = PyObject_GetItem(__pyx_v_args, __pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}
    Py_DECREF(__pyx_v_spam);
    __pyx_v_spam = __pyx_4;
    __pyx_4 = 0;

    /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":250 */
    __pyx_1 = PyString_AsString(__pyx_v_spam); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
    __pyx_2 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
    (__pyx_v_hist[__pyx_2]) = ngram_wid(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_1);
  }

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":251 */
  __pyx_v_score = ngram_ng_score(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_v_wid,__pyx_v_hist,__pyx_v_n_hist,(&__pyx_v_n_used));

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":252 */
  ckd_free(__pyx_v_hist);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":253 */
  __pyx_4 = PyFloat_FromDouble(logmath_log_to_ln(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lmath,__pyx_v_score)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_n_used); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 253; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_5);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_r = __pyx_6;
  __pyx_6 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("sphinxbase.NGramModel.score");
  __pyx_r = 0;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_spam);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_word);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_prob(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_10sphinxbase_10NGramModel_prob[] = "\n        Get the log-probability for an N-Gram.\n\n        This works effectively the same way as L{score}, except that\n        any weights (language weight, insertion penalty) applied to\n        the language model are ignored and the \"raw\" probability value\n        is returned.\n        ";
static PyObject *__pyx_f_10sphinxbase_10NGramModel_prob(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_word = 0;
  PyObject *__pyx_v_args = 0;
  __pyx_t_10sphinxbase_int32 __pyx_v_wid;
  __pyx_t_10sphinxbase_int32 *__pyx_v_hist;
  __pyx_t_10sphinxbase_int32 __pyx_v_n_hist;
  __pyx_t_10sphinxbase_int32 __pyx_v_n_used;
  __pyx_t_10sphinxbase_int32 __pyx_v_score;
  PyObject *__pyx_v_i;
  PyObject *__pyx_v_spam;
  PyObject *__pyx_r;
  char *__pyx_1;
  Py_ssize_t __pyx_2;
  long __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"word",0};
  if (__Pyx_GetStarArgs(&__pyx_args, &__pyx_kwds, __pyx_argnames, 1, &__pyx_v_args, 0, 0) < 0) return 0;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_word)) {
    Py_XDECREF(__pyx_args);
    Py_XDECREF(__pyx_kwds);
    Py_XDECREF(__pyx_v_args);
    return 0;
  }
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_word);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);
  __pyx_v_spam = Py_None; Py_INCREF(Py_None);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":269 */
  __pyx_1 = PyString_AsString(__pyx_v_word); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 269; goto __pyx_L1;}
  __pyx_v_wid = ngram_wid(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_1);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":270 */
  __pyx_2 = PyObject_Length(__pyx_v_args); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 270; goto __pyx_L1;}
  __pyx_v_n_hist = __pyx_2;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":271 */
  __pyx_v_hist = ((__pyx_t_10sphinxbase_int32 *)ckd_calloc(__pyx_v_n_hist,(sizeof(__pyx_t_10sphinxbase_int32))));

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":272 */
  for (__pyx_3 = 0; __pyx_3 < __pyx_v_n_hist; ++__pyx_3) {
    __pyx_4 = PyInt_FromLong(__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 272; goto __pyx_L1;}
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_4;
    __pyx_4 = 0;

    /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":273 */
    __pyx_4 = PyObject_GetItem(__pyx_v_args, __pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 273; goto __pyx_L1;}
    Py_DECREF(__pyx_v_spam);
    __pyx_v_spam = __pyx_4;
    __pyx_4 = 0;

    /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":274 */
    __pyx_1 = PyString_AsString(__pyx_v_spam); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
    __pyx_2 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 274; goto __pyx_L1;}
    (__pyx_v_hist[__pyx_2]) = ngram_wid(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_1);
  }

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":275 */
  __pyx_v_score = ngram_ng_prob(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_v_wid,__pyx_v_hist,__pyx_v_n_hist,(&__pyx_v_n_used));

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":276 */
  ckd_free(__pyx_v_hist);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":277 */
  __pyx_4 = PyFloat_FromDouble(logmath_log_to_ln(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lmath,__pyx_v_score)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 277; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_n_used); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 277; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 277; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_4);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_5);
  __pyx_4 = 0;
  __pyx_5 = 0;
  __pyx_r = __pyx_6;
  __pyx_6 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("sphinxbase.NGramModel.prob");
  __pyx_r = 0;
  __pyx_L0:;
  Py_XDECREF(__pyx_v_args);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_spam);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_word);
  Py_XDECREF(__pyx_args);
  Py_XDECREF(__pyx_kwds);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_10NGramModel_mgrams(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_10sphinxbase_10NGramModel_mgrams(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_m = 0;
  struct __pyx_obj_10sphinxbase_NGramIter *__pyx_v_itor;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {"m",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_m)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_m);
  __pyx_v_itor = ((struct __pyx_obj_10sphinxbase_NGramIter *)Py_None); Py_INCREF(Py_None);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":281 */
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 281; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_self);
  Py_INCREF(__pyx_v_m);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_m);
  __pyx_2 = PyObject_CallObject(((PyObject *)__pyx_ptype_10sphinxbase_NGramIter), __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 281; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((PyObject *)__pyx_v_itor));
  __pyx_v_itor = ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_2);
  __pyx_2 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":282 */
  __pyx_3 = PyInt_AsLong(__pyx_v_m); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 282; goto __pyx_L1;}
  __pyx_v_itor->itor = ngram_model_mgrams(((struct __pyx_obj_10sphinxbase_NGramModel *)__pyx_v_self)->lm,__pyx_3);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":283 */
  __pyx_3 = (__pyx_v_itor->itor == NULL);
  if (__pyx_3) {
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":285 */
  Py_INCREF(((PyObject *)__pyx_v_itor));
  __pyx_r = ((PyObject *)__pyx_v_itor);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.NGramModel.mgrams");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_itor);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_m);
  return __pyx_r;
}

static int __pyx_f_10sphinxbase_9NGramIter___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_10sphinxbase_9NGramIter___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_10sphinxbase_NGramModel *__pyx_v_lm = 0;
  int __pyx_v_m;
  int __pyx_r;
  int __pyx_1;
  static char *__pyx_argnames[] = {"lm","m",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "Oi", __pyx_argnames, &__pyx_v_lm, &__pyx_v_m)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_lm);
  if (!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_lm), __pyx_ptype_10sphinxbase_NGramModel, 1, "lm")) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 294; goto __pyx_L1;}

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":295 */
  ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->itor = NULL;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":296 */
  Py_INCREF(((PyObject *)__pyx_v_lm));
  Py_DECREF(((PyObject *)((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->lm));
  ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->lm = __pyx_v_lm;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":297 */
  ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->m = __pyx_v_m;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":298 */
  __pyx_1 = PyInt_AsLong(Py_True); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 298; goto __pyx_L1;}
  ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->first_item = __pyx_1;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("sphinxbase.NGramIter.__cinit__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_lm);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_9NGramIter___iter__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_10sphinxbase_9NGramIter___iter__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_self);
  __pyx_r = __pyx_v_self;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_9NGramIter___next__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_10sphinxbase_9NGramIter___next__(PyObject *__pyx_v_self) {
  __pyx_t_10sphinxbase_int32 __pyx_v_prob;
  __pyx_t_10sphinxbase_int32 __pyx_v_bowt;
  __pyx_t_10sphinxbase_int32 *__pyx_v_wids;
  struct __pyx_obj_10sphinxbase_NGram *__pyx_v_ng;
  PyObject *__pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_ssize_t __pyx_6;
  Py_INCREF(__pyx_v_self);
  __pyx_v_ng = ((struct __pyx_obj_10sphinxbase_NGram *)Py_None); Py_INCREF(Py_None);
  __pyx_v_i = Py_None; Py_INCREF(Py_None);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":307 */
  __pyx_1 = ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->first_item;
  if (__pyx_1) {
    __pyx_1 = PyInt_AsLong(Py_False); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 308; goto __pyx_L1;}
    ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->first_item = __pyx_1;
    goto __pyx_L2;
  }
  /*else*/ {
    ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->itor = ngram_iter_next(((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->itor);
  }
  __pyx_L2:;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":311 */
  __pyx_1 = (((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->itor == NULL);
  if (__pyx_1) {
    __Pyx_Raise(PyExc_StopIteration, 0, 0);
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 312; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":313 */
  __pyx_v_wids = ngram_iter_get(((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->itor,(&__pyx_v_prob),(&__pyx_v_bowt));

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":314 */
  __pyx_2 = PyObject_CallObject(((PyObject *)__pyx_ptype_10sphinxbase_NGram), 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 314; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_v_ng));
  __pyx_v_ng = ((struct __pyx_obj_10sphinxbase_NGram *)__pyx_2);
  __pyx_2 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":315 */
  __pyx_v_ng->log_prob = logmath_log_to_ln(((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->lm->lmath,__pyx_v_prob);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":316 */
  __pyx_v_ng->log_bowt = logmath_log_to_ln(((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->lm->lmath,__pyx_v_bowt);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":317 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 317; goto __pyx_L1;}
  Py_DECREF(__pyx_v_ng->words);
  __pyx_v_ng->words = __pyx_2;
  __pyx_2 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":318 */
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong((((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->m + 1)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
  __pyx_3 = 0;
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_4 = PyObject_GetIter(__pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_2 = PyIter_Next(__pyx_4);
    if (!__pyx_2) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 318; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_i);
    __pyx_v_i = __pyx_2;
    __pyx_2 = 0;
    __pyx_5 = PyObject_GetAttr(__pyx_v_ng->words, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 319; goto __pyx_L1;}
    __pyx_6 = PyInt_AsSsize_t(__pyx_v_i); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 319; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(ngram_word(((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->lm->lm,(__pyx_v_wids[__pyx_6]))); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 319; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 319; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_3);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_5, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 319; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":320 */
  Py_INCREF(((PyObject *)__pyx_v_ng));
  __pyx_r = ((PyObject *)__pyx_v_ng);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("sphinxbase.NGramIter.__next__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ng);
  Py_DECREF(__pyx_v_i);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_10sphinxbase_9NGramIter_successors(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_10sphinxbase_9NGramIter_successors(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_10sphinxbase_NGramIter *__pyx_v_itor;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_itor = ((struct __pyx_obj_10sphinxbase_NGramIter *)Py_None); Py_INCREF(Py_None);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":324 */
  __pyx_1 = PyInt_FromLong((((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->m - 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 324; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 324; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->lm));
  PyTuple_SET_ITEM(__pyx_2, 0, ((PyObject *)((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->lm));
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyObject_CallObject(((PyObject *)__pyx_ptype_10sphinxbase_NGramIter), __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 324; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_v_itor));
  __pyx_v_itor = ((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_1);
  __pyx_1 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":325 */
  __pyx_v_itor->itor = ngram_iter_successors(((struct __pyx_obj_10sphinxbase_NGramIter *)__pyx_v_self)->itor);

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":326 */
  __pyx_3 = (__pyx_v_itor->itor == NULL);
  if (__pyx_3) {
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":328 */
  Py_INCREF(((PyObject *)__pyx_v_itor));
  __pyx_r = ((PyObject *)__pyx_v_itor);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("sphinxbase.NGramIter.successors");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_itor);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}
static struct __pyx_vtabstruct_10sphinxbase_NGramModel __pyx_vtable_10sphinxbase_NGramModel;

static PyObject *__pyx_tp_new_10sphinxbase_NGramModel(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_10sphinxbase_NGramModel *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_10sphinxbase_NGramModel *)o);
  *(struct __pyx_vtabstruct_10sphinxbase_NGramModel **)&p->__pyx_vtab = __pyx_vtabptr_10sphinxbase_NGramModel;
  if (__pyx_f_10sphinxbase_10NGramModel___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_10sphinxbase_NGramModel(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_10sphinxbase_10NGramModel___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_10sphinxbase_NGramModel[] = {
  {"apply_weights", (PyCFunction)__pyx_f_10sphinxbase_10NGramModel_apply_weights, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_10NGramModel_apply_weights},
  {"wid", (PyCFunction)__pyx_f_10sphinxbase_10NGramModel_wid, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_10NGramModel_wid},
  {"word", (PyCFunction)__pyx_f_10sphinxbase_10NGramModel_word, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_10NGramModel_word},
  {"score", (PyCFunction)__pyx_f_10sphinxbase_10NGramModel_score, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_10NGramModel_score},
  {"prob", (PyCFunction)__pyx_f_10sphinxbase_10NGramModel_prob, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_10NGramModel_prob},
  {"mgrams", (PyCFunction)__pyx_f_10sphinxbase_10NGramModel_mgrams, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_10sphinxbase_NGramModel[] = {
  {"lw", T_FLOAT, offsetof(struct __pyx_obj_10sphinxbase_NGramModel, lw), READONLY, 0},
  {"wip", T_FLOAT, offsetof(struct __pyx_obj_10sphinxbase_NGramModel, wip), READONLY, 0},
  {"uw", T_FLOAT, offsetof(struct __pyx_obj_10sphinxbase_NGramModel, uw), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_NGramModel = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_NGramModel = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_NGramModel = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_NGramModel = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_10sphinxbase_NGramModel = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "sphinxbase.NGramModel", /*tp_name*/
  sizeof(struct __pyx_obj_10sphinxbase_NGramModel), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_10sphinxbase_NGramModel, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_NGramModel, /*tp_as_number*/
  &__pyx_tp_as_sequence_NGramModel, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_NGramModel, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_NGramModel, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  "\n    N-Gram language model class.\n\n    This class provides access to N-Gram language models stored on\n    disk.  These can be in ARPABO text format or Sphinx DMP format.\n    Methods are provided for scoring N-Grams based on the model,\n    looking up words in the model, and adding words to the model.\n    ", /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_10sphinxbase_NGramModel, /*tp_methods*/
  __pyx_members_10sphinxbase_NGramModel, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_10sphinxbase_NGramModel, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_10sphinxbase_LogMath(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  if (__pyx_f_10sphinxbase_7LogMath___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_10sphinxbase_LogMath(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_10sphinxbase_7LogMath___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_10sphinxbase_LogMath[] = {
  {"get_zero", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_get_zero, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_get_zero},
  {"add", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_add, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_add},
  {"log", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_log, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_log},
  {"exp", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_exp, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_exp},
  {"log_to_ln", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_log_to_ln, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_log_to_ln},
  {"log_to_log10", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_log_to_log10, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_log_to_log10},
  {"ln_to_log", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_ln_to_log, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_ln_to_log},
  {"log10_to_log", (PyCFunction)__pyx_f_10sphinxbase_7LogMath_log10_to_log, METH_VARARGS|METH_KEYWORDS, __pyx_doc_10sphinxbase_7LogMath_log10_to_log},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_LogMath = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_LogMath = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_LogMath = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_LogMath = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_10sphinxbase_LogMath = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "sphinxbase.LogMath", /*tp_name*/
  sizeof(struct __pyx_obj_10sphinxbase_LogMath), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_10sphinxbase_LogMath, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_LogMath, /*tp_as_number*/
  &__pyx_tp_as_sequence_LogMath, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_LogMath, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_LogMath, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  "\n    Log-space math class.\n    \n    This class provides fast logarithmic math functions in base\n    1.000+epsilon, useful for fixed point speech recognition.\n    ", /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_10sphinxbase_LogMath, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_10sphinxbase_LogMath, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_10sphinxbase_NGram(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_10sphinxbase_NGram *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_10sphinxbase_NGram *)o);
  p->words = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_10sphinxbase_NGram(PyObject *o) {
  struct __pyx_obj_10sphinxbase_NGram *p = (struct __pyx_obj_10sphinxbase_NGram *)o;
  Py_XDECREF(p->words);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_10sphinxbase_NGram(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_10sphinxbase_NGram *p = (struct __pyx_obj_10sphinxbase_NGram *)o;
  if (p->words) {
    e = (*v)(p->words, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_10sphinxbase_NGram(PyObject *o) {
  struct __pyx_obj_10sphinxbase_NGram *p = (struct __pyx_obj_10sphinxbase_NGram *)o;
  PyObject *t;
  t = p->words; 
  p->words = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_10sphinxbase_NGram[] = {
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_10sphinxbase_NGram[] = {
  {"log_prob", T_FLOAT, offsetof(struct __pyx_obj_10sphinxbase_NGram, log_prob), READONLY, 0},
  {"log_bowt", T_FLOAT, offsetof(struct __pyx_obj_10sphinxbase_NGram, log_bowt), READONLY, 0},
  {"words", T_OBJECT, offsetof(struct __pyx_obj_10sphinxbase_NGram, words), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_NGram = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_NGram = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_NGram = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_NGram = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_10sphinxbase_NGram = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "sphinxbase.NGram", /*tp_name*/
  sizeof(struct __pyx_obj_10sphinxbase_NGram), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_10sphinxbase_NGram, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_NGram, /*tp_as_number*/
  &__pyx_tp_as_sequence_NGram, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_NGram, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_NGram, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_10sphinxbase_NGram, /*tp_traverse*/
  __pyx_tp_clear_10sphinxbase_NGram, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_10sphinxbase_NGram, /*tp_methods*/
  __pyx_members_10sphinxbase_NGram, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_10sphinxbase_NGram, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_10sphinxbase_NGramIter(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_10sphinxbase_NGramIter *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_10sphinxbase_NGramIter *)o);
  p->lm = ((struct __pyx_obj_10sphinxbase_NGramModel *)Py_None); Py_INCREF(Py_None);
  if (__pyx_f_10sphinxbase_9NGramIter___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_10sphinxbase_NGramIter(PyObject *o) {
  struct __pyx_obj_10sphinxbase_NGramIter *p = (struct __pyx_obj_10sphinxbase_NGramIter *)o;
  Py_XDECREF(((PyObject *)p->lm));
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_10sphinxbase_NGramIter(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_10sphinxbase_NGramIter *p = (struct __pyx_obj_10sphinxbase_NGramIter *)o;
  if (p->lm) {
    e = (*v)(((PyObject*)p->lm), a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_10sphinxbase_NGramIter(PyObject *o) {
  struct __pyx_obj_10sphinxbase_NGramIter *p = (struct __pyx_obj_10sphinxbase_NGramIter *)o;
  PyObject *t;
  t = ((PyObject *)p->lm); 
  p->lm = ((struct __pyx_obj_10sphinxbase_NGramModel *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_10sphinxbase_NGramIter[] = {
  {"successors", (PyCFunction)__pyx_f_10sphinxbase_9NGramIter_successors, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_NGramIter = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_NGramIter = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_NGramIter = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_NGramIter = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_10sphinxbase_NGramIter = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "sphinxbase.NGramIter", /*tp_name*/
  sizeof(struct __pyx_obj_10sphinxbase_NGramIter), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_10sphinxbase_NGramIter, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_NGramIter, /*tp_as_number*/
  &__pyx_tp_as_sequence_NGramIter, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_NGramIter, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_NGramIter, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "\n    N-Gram language model iterator class.\n\n    This class provides access to the individual N-grams stored in a\n    language model.\n    ", /*tp_doc*/
  __pyx_tp_traverse_10sphinxbase_NGramIter, /*tp_traverse*/
  __pyx_tp_clear_10sphinxbase_NGramIter, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  __pyx_f_10sphinxbase_9NGramIter___iter__, /*tp_iter*/
  __pyx_f_10sphinxbase_9NGramIter___next__, /*tp_iternext*/
  __pyx_methods_10sphinxbase_NGramIter, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_10sphinxbase_NGramIter, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initsphinxbase(void); /*proto*/
PyMODINIT_FUNC initsphinxbase(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  PyObject *__pyx_7 = 0;
  PyObject *__pyx_8 = 0;
  PyObject *__pyx_9 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("sphinxbase", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;};
  __pyx_vtabptr_10sphinxbase_NGramModel = &__pyx_vtable_10sphinxbase_NGramModel;
  *(void(**)(void))&__pyx_vtable_10sphinxbase_NGramModel.set_lm = (void(*)(void))__pyx_f_10sphinxbase_10NGramModel_set_lm;
  *(void(**)(void))&__pyx_vtable_10sphinxbase_NGramModel.set_lmath = (void(*)(void))__pyx_f_10sphinxbase_10NGramModel_set_lmath;
  if (PyType_Ready(&__pyx_type_10sphinxbase_NGramModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_10sphinxbase_NGramModel.tp_dict, __pyx_vtabptr_10sphinxbase_NGramModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "NGramModel", (PyObject *)&__pyx_type_10sphinxbase_NGramModel) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
  __pyx_ptype_10sphinxbase_NGramModel = &__pyx_type_10sphinxbase_NGramModel;
  if (PyType_Ready(&__pyx_type_10sphinxbase_LogMath) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "LogMath", (PyObject *)&__pyx_type_10sphinxbase_LogMath) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  __pyx_ptype_10sphinxbase_LogMath = &__pyx_type_10sphinxbase_LogMath;
  __pyx_type_10sphinxbase_NGram.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_10sphinxbase_NGram) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 104; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "NGram", (PyObject *)&__pyx_type_10sphinxbase_NGram) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 104; goto __pyx_L1;}
  __pyx_ptype_10sphinxbase_NGram = &__pyx_type_10sphinxbase_NGram;
  __pyx_type_10sphinxbase_NGramIter.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_10sphinxbase_NGramIter) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 287; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "NGramIter", (PyObject *)&__pyx_type_10sphinxbase_NGramIter) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 287; goto __pyx_L1;}
  __pyx_ptype_10sphinxbase_NGramIter = &__pyx_type_10sphinxbase_NGramIter;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":17 */
  __pyx_1 = PyFloat_FromDouble(1.0001); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  __pyx_d1 = __pyx_1;
  __pyx_1 = 0;
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  __pyx_d2 = __pyx_2;
  __pyx_2 = 0;
  __pyx_3 = PyInt_FromLong(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  __pyx_d3 = __pyx_3;
  __pyx_3 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":133 */
  Py_INCREF(Py_None);
  __pyx_d4 = Py_None;
  __pyx_4 = PyFloat_FromDouble(1.0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_d5 = __pyx_4;
  __pyx_4 = 0;
  __pyx_5 = PyFloat_FromDouble(1.0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_d6 = __pyx_5;
  __pyx_5 = 0;
  __pyx_6 = PyFloat_FromDouble(1.0); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
  __pyx_d7 = __pyx_6;
  __pyx_6 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":173 */
  __pyx_7 = PyFloat_FromDouble(1.0); if (!__pyx_7) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_d8 = __pyx_7;
  __pyx_7 = 0;
  __pyx_8 = PyFloat_FromDouble(1.0); if (!__pyx_8) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_d9 = __pyx_8;
  __pyx_8 = 0;
  __pyx_9 = PyFloat_FromDouble(1.0); if (!__pyx_9) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 173; goto __pyx_L1;}
  __pyx_d10 = __pyx_9;
  __pyx_9 = 0;

  /* "/home/dhuggins/Projects/Sphinx/sphinxbase/python/sphinxbase.pyx":322 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  Py_XDECREF(__pyx_7);
  Py_XDECREF(__pyx_8);
  Py_XDECREF(__pyx_9);
  __Pyx_AddTraceback("sphinxbase");
}

static char *__pyx_filenames[] = {
  "sphinxbase.pyx",
  "sphinxbase.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_GetStarArgs(
    PyObject **args, 
    PyObject **kwds,
    char *kwd_list[], 
    Py_ssize_t nargs,
    PyObject **args2, 
    PyObject **kwds2,
    char rqd_kwds[])
{
    PyObject *x = 0, *args1 = 0, *kwds1 = 0;
    int i;
    char **p;
    
    if (args2)
        *args2 = 0;
    if (kwds2)
        *kwds2 = 0;
    
    if (args2) {
        args1 = PyTuple_GetSlice(*args, 0, nargs);
        if (!args1)
            goto bad;
        *args2 = PyTuple_GetSlice(*args, nargs, PyTuple_GET_SIZE(*args));
        if (!*args2)
            goto bad;
    }
    else if (PyTuple_GET_SIZE(*args) > nargs) {
        int m = nargs;
        int n = PyTuple_GET_SIZE(*args);
        PyErr_Format(PyExc_TypeError,
            "function takes at most %d positional arguments (%d given)",
                m, n);
        goto bad;
    }
    else {
        args1 = *args;
        Py_INCREF(args1);
    }
    
    if (rqd_kwds && !*kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i])
                    goto missing_kwarg;
    
    if (kwds2) {
        if (*kwds) {
            kwds1 = PyDict_New();
            if (!kwds1)
                goto bad;
            *kwds2 = PyDict_Copy(*kwds);
            if (!*kwds2)
                goto bad;
            for (i = 0, p = kwd_list; *p; i++, p++) {
                x = PyDict_GetItemString(*kwds, *p);
                if (x) {
                    if (PyDict_SetItemString(kwds1, *p, x) < 0)
                        goto bad;
                    if (PyDict_DelItemString(*kwds2, *p) < 0)
                        goto bad;
                }
                else if (rqd_kwds && rqd_kwds[i])
                    goto missing_kwarg;
            }
        }
        else {
            *kwds2 = PyDict_New();
            if (!*kwds2)
                goto bad;
        }
    }
    else {
        kwds1 = *kwds;
        Py_XINCREF(kwds1);
        if (rqd_kwds && *kwds)
            for (i = 0, p = kwd_list; *p; i++, p++)
                if (rqd_kwds[i] && !PyDict_GetItemString(*kwds, *p))
                        goto missing_kwarg;
    }
    
    *args = args1;
    *kwds = kwds1;
    return 0;
missing_kwarg:
    PyErr_Format(PyExc_TypeError,
        "required keyword argument '%s' is missing", *p);
bad:
    Py_XDECREF(args1);
    Py_XDECREF(kwds1);
    if (args2) {
        Py_XDECREF(*args2);
    }
    if (kwds2) {
        Py_XDECREF(*kwds2);
    }
    return -1;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if ((none_allowed && obj == Py_None) || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, obj->ob_type->tp_name);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
